[package]
name = "llm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib"]

[dependencies]
miniserde = { workspace = true }
network = { path = "../network", default-features = false }
smoltcp = { workspace = true }

[features]
default = ["tls"]
tls = ["network/tls"]
